server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # THIS IS THE MAGIC LINE FOR REACT ROUTER:
        try_files $uri $uri/ /index.html;
    }
}