spring:
  application:
    name: eureka-server

#Registered as Eureka server
eureka:
  instance:
    secure-port-enabled: false
    non-secure-port-enabled: true
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761
